services:
  hontokun-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - front_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    tty: true

volumes:
  front_node_modules: