services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
       - .:/app
       - front_node_modules:/app/node_modules
    networks:
      - hontokun

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: hontokun
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
        - hontokun

networks:
  hontokun:
    external: true

volumes:
  front_node_modules:
