name: 'image build_push'
on:
  push:
    branches:
      - feature/#24_build-push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: "set up checkout"
      uses: actions/checkout@v4
    - name: "set up docker buildx"
      uses: docker/setup-buildx-action@v3
      

    - name: Debug Docker Hub Username
      run: echo "$DOCKER_USERNAME"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: Decode Firebase service account key
      run: echo "$FIREBASE_SERVICE_JSON" | base64 -d > ./service-account.json
      env:
        FIREBASE_SERVICE_JSON: ${{ secrets.FIREBASE_SERVICE_JSON }}
  

    - name: "docker-login"
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: "build-push"
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: true
        tags:  kouxi00/hontokun-backend:1.0.0
