name: 'image build_push'
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: "set up checkout"
      uses: actions/checkout@v4
    - name: "set up docker buildx"
      uses: docker/setup-buildx-action@v3
    - name: "docker-login"
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: "create metadata"
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/
        tags: |
          type=raw,value=latest
          type=sha,prefix=,suffix=,format=short
    - name: "build-push"
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64 
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }} # 前ステップで設定したタグを参照する
        labels: ${{ steps.meta.outputs.labels }} # 前ステップで設定したラベルを参照する
